use std::collections::HashMap;
use std::error::Error;
use std::fs;
use std::path::Path;

use crate::calibration_pass;
use crate::layout_pass;
use crate::types::*;
use crate::util;

// Legacy ManifestFiles struct for compile output
#[derive(Debug, Clone, serde::Serialize)]
struct CompileManifest {
    schema_version: u32,
    pack_type: &'static str,
    model_family: &'static str,
    model_name: String,
    target: String,
    created_at: String,
    files: CompileManifestFiles,
    notes: String,
}

#[derive(Debug, Clone, serde::Serialize)]
struct CompileManifestFiles {
    expert_layout: &'static str,
    expert_importance: &'static str,
    expert_coresidency: &'static str,
    residency_plan: &'static str,
    phase_policy: &'static str,
    runtime_profile: &'static str,
}

pub fn compile_runtime_pack(
    model: &Path,
    calib: Option<&Path>,
    target: &str,
    cache_capacity: Option<u64>,
    expert_bytes: Option<u64>,
    out: &Path,
    _format: super::OutputFormat,
) -> Result<(), Box<dyn Error>> {
    fs::create_dir_all(out)?;

    let runtime_cache_capacity = cache_capacity.unwrap_or_else(|| default_cache_capacity(target));
    let model_files = util::resolve_model_files(model)?;
    let model_config: ModelConfig =
        serde_json::from_str(&fs::read_to_string(&model_files.config_path)?)?;
    let index: SafeTensorsIndex =
        serde_json::from_str(&fs::read_to_string(&model_files.index_path)?)?;
    let model_name = util::infer_model_name(model, &model_config);
    let created_at = util::now_rfc3339ish();
    let expert_layout = layout_pass::run(&model_name, &model_config, &index)?;

    let manifest = CompileManifest {
        schema_version: 1,
        pack_type: "objeta_runtime_pack",
        model_family: "qwen",
        model_name: model_name.clone(),
        target: target.to_string(),
        created_at,
        files: CompileManifestFiles {
            expert_layout: "expert_layout.json",
            expert_importance: "expert_importance.json",
            expert_coresidency: "expert_coresidency.json",
            residency_plan: "residency_plan.json",
            phase_policy: "phase_policy.json",
            runtime_profile: "runtime_profile.json",
        },
        notes: format!(
            "Generated by objeta-aot v0 from {} tensors (total_size={:?}, calib={})",
            index.weight_map.len(),
            index.metadata.total_size,
            calib.is_some()
        ),
    };

    let (expert_importance, expert_coresidency) = if let Some(calib_path) = calib {
        let stats = calibration_pass::run(calib_path)?;
        (stats.importance, stats.coresidency)
    } else {
        (
            ExpertImportance {
                schema_version: 1,
                experts: Vec::new(),
            },
            ExpertCoresidency {
                schema_version: 1,
                pairs: Vec::new(),
            },
        )
    };

    let residency_plan = build_residency_plan(
        &expert_layout,
        &expert_importance,
        &expert_coresidency,
        target,
        runtime_cache_capacity,
        expert_bytes,
    );

    let phase_policy = PhasePolicy {
        schema_version: 1,
        source: "heuristic_lko_v1".to_string(),
        confidence: "experimental".to_string(),
        layers: vec![
            PhasePolicyLayer {
                layer: 0,
                phase: "integrity_frontier".to_string(),
                recommended_policy: RecommendedPolicy {
                    policy_kind: "exact".to_string(),
                    moe_top_p: 1.0,
                    moe_min_experts: 8,
                    moe_max_experts: 8,
                },
            },
            PhasePolicyLayer {
                layer: 23,
                phase: "transport".to_string(),
                recommended_policy: RecommendedPolicy {
                    policy_kind: "top_p".to_string(),
                    moe_top_p: 0.90,
                    moe_min_experts: 4,
                    moe_max_experts: 8,
                },
            },
        ],
    };

    let runtime_profile = RuntimeProfile {
        schema_version: 1,
        profile_name: format!("{model_name}-{target}-planner"),
        target: target.to_string(),
        backend: "fused_row_parallel".to_string(),
        policy_kind: "top_p".to_string(),
        moe_top_p: 0.90,
        moe_min_experts: 4,
        moe_max_experts: 8,
        resident_cache_capacity_bytes: residency_plan.resident_cache_capacity_bytes,
        group_preresolve_top_n: 0,
        group_preresolve_max_bytes: 0,
        source_model: model.display().to_string(),
        source_calibration: calib.map(|p| p.display().to_string()),
    };

    util::write_json(out.join("manifest.json"), &manifest)?;
    util::write_json(out.join("expert_layout.json"), &expert_layout)?;
    util::write_json(out.join("expert_importance.json"), &expert_importance)?;
    util::write_json(out.join("expert_coresidency.json"), &expert_coresidency)?;
    util::write_json(out.join("residency_plan.json"), &residency_plan)?;
    util::write_json(out.join("phase_policy.json"), &phase_policy)?;
    util::write_json(out.join("runtime_profile.json"), &runtime_profile)?;

    println!("Wrote runtime pack: {}", out.display());
    println!("  model:   {}", model.display());
    if let Some(calib) = calib {
        println!("  calib:   {}", calib.display());
    }
    println!("  target:  {}", target);
    println!("  backend: {}", runtime_profile.backend);
    println!(
        "  policy:  {} (top_p={}, min={}, max={})",
        runtime_profile.policy_kind,
        runtime_profile.moe_top_p,
        runtime_profile.moe_min_experts,
        runtime_profile.moe_max_experts
    );
    println!(
        "  cache:   {} bytes",
        runtime_profile.resident_cache_capacity_bytes
    );
    println!(
        "  layout:  {} routed experts, {} shared experts, {} routers, {} unknown, {} warnings",
        expert_layout.experts.len(),
        expert_layout.shared_experts.len(),
        expert_layout.routers.len(),
        expert_layout.unknown_tensors.len(),
        expert_layout.warnings.len()
    );
    println!(
        "  calib:   {} importance entries, {} co-residency pairs",
        expert_importance.experts.len(),
        expert_coresidency.pairs.len()
    );
    println!(
        "  planner: {} hot experts / {} bytes, {} eviction entries",
        residency_plan.summary.initial_hot_expert_count,
        residency_plan.summary.initial_hot_expert_bytes,
        residency_plan.summary.eviction_priority_count
    );

    Ok(())
}

pub fn build_residency_plan(
    layout: &ExpertLayout,
    importance: &ExpertImportance,
    _coresidency: &ExpertCoresidency,
    target: &str,
    resident_cache_capacity_bytes: u64,
    expert_bytes_override: Option<u64>,
) -> ResidencyPlan {
    let planned = build_planned_experts(layout, importance, target, expert_bytes_override);

    let mut sorted_for_hot = planned.clone();
    sorted_for_hot.sort_by(|a, b| {
        b.importance
            .partial_cmp(&a.importance)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| match (&a.tier, &b.tier) {
                (ExpertTier::Hot, ExpertTier::Hot)
                | (ExpertTier::Warm, ExpertTier::Warm)
                | (ExpertTier::Cold, ExpertTier::Cold) => std::cmp::Ordering::Equal,
                (ExpertTier::Hot, _) => std::cmp::Ordering::Less,
                (_, ExpertTier::Hot) => std::cmp::Ordering::Greater,
                (ExpertTier::Warm, _) => std::cmp::Ordering::Less,
                (_, ExpertTier::Warm) => std::cmp::Ordering::Greater,
            })
            .then_with(|| a.layer.cmp(&b.layer))
            .then_with(|| a.expert.cmp(&b.expert))
    });

    let mut hot_bytes = 0u64;
    let mut initial_hot_experts = Vec::new();
    for expert in &sorted_for_hot {
        if expert.bytes == 0 {
            continue;
        }
        if hot_bytes.saturating_add(expert.bytes) > resident_cache_capacity_bytes {
            continue;
        }
        hot_bytes = hot_bytes.saturating_add(expert.bytes);
        initial_hot_experts.push(PlannedHotExpert {
            layer: expert.layer,
            expert: expert.expert,
            bytes: expert.bytes,
            importance: expert.importance,
            tier: expert.tier.clone(),
            bytes_source: expert.bytes_source.clone(),
        });
    }

    let mut eviction_sorted = planned;
    eviction_sorted.sort_by(|a, b| {
        tier_rank(&a.tier)
            .cmp(&tier_rank(&b.tier))
            .then_with(|| {
                a.importance
                    .partial_cmp(&b.importance)
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
            .then_with(|| a.selected_count.cmp(&b.selected_count))
            .then_with(|| {
                a.avg_gate_weight
                    .partial_cmp(&b.avg_gate_weight)
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
            .then_with(|| a.layer.cmp(&b.layer))
            .then_with(|| a.expert.cmp(&b.expert))
    });
    let eviction_priority: Vec<_> = eviction_sorted
        .into_iter()
        .enumerate()
        .map(|(idx, expert)| EvictionPriorityEntry {
            layer: expert.layer,
            expert: expert.expert,
            priority: idx as f64 / (layout.experts.len().max(1) as f64),
            tier: expert.tier,
            importance: expert.importance,
            selected_count: expert.selected_count,
            avg_gate_weight: expert.avg_gate_weight,
            bytes: expert.bytes,
            bytes_source: expert.bytes_source,
        })
        .collect();

    let bytes_fallback_expert_count = initial_hot_experts
        .iter()
        .filter(|e| e.bytes_source != "layout_total_bytes")
        .count();
    let initial_hot_expert_count = initial_hot_experts.len();
    let eviction_priority_count = eviction_priority.len();

    ResidencyPlan {
        schema_version: 1,
        target: target.to_string(),
        resident_cache_capacity_bytes,
        initial_hot_experts,
        eviction_priority,
        summary: ResidencyPlanSummary {
            initial_hot_expert_count,
            initial_hot_expert_bytes: hot_bytes,
            eviction_priority_count,
            bytes_fallback_expert_count,
        },
    }
}

fn build_planned_experts(
    layout: &ExpertLayout,
    importance: &ExpertImportance,
    target: &str,
    expert_bytes_override: Option<u64>,
) -> Vec<PlannedExpert> {
    let layout_map: HashMap<ExpertKey, &ExpertEntry> = layout
        .experts
        .iter()
        .map(|entry| {
            (
                ExpertKey {
                    layer: entry.layer,
                    expert: entry.expert,
                },
                entry,
            )
        })
        .collect();

    importance
        .experts
        .iter()
        .map(|entry| {
            let key = ExpertKey {
                layer: entry.layer,
                expert: entry.expert,
            };
            let (bytes, bytes_source) = resolve_expert_bytes(
                layout_map.get(&key).copied(),
                target,
                expert_bytes_override,
            );
            PlannedExpert {
                layer: entry.layer,
                expert: entry.expert,
                importance: entry.importance,
                tier: entry.tier.clone(),
                selected_count: entry.selected_count,
                avg_gate_weight: entry.avg_gate_weight,
                bytes,
                bytes_source,
            }
        })
        .collect()
}

fn resolve_expert_bytes(
    expert: Option<&ExpertEntry>,
    target: &str,
    expert_bytes_override: Option<u64>,
) -> (u64, String) {
    let layout_total_bytes = expert
        .map(sum_expert_tensor_bytes)
        .filter(|bytes| *bytes > 0);
    if let Some(bytes) = layout_total_bytes {
        return (bytes, "layout_total_bytes".to_string());
    }
    if let Some(bytes) = expert_bytes_override {
        return (bytes, "expert_bytes_override".to_string());
    }
    (
        default_expert_bytes(target),
        "target_default_estimate".to_string(),
    )
}

fn sum_expert_tensor_bytes(expert: &ExpertEntry) -> u64 {
    [
        expert.gate.as_ref(),
        expert.up.as_ref(),
        expert.gate_up.as_ref(),
        expert.down.as_ref(),
    ]
    .into_iter()
    .flatten()
    .filter_map(|t| t.byte_len)
    .sum()
}

fn default_expert_bytes(target: &str) -> u64 {
    match target {
        "m1-8gb" => 2 * 1024 * 1024,
        "m2-16gb" => 3 * 1024 * 1024,
        _ => 2 * 1024 * 1024,
    }
}

fn tier_rank(tier: &ExpertTier) -> u8 {
    match tier {
        ExpertTier::Cold => 0,
        ExpertTier::Warm => 1,
        ExpertTier::Hot => 2,
    }
}

fn default_cache_capacity(target: &str) -> u64 {
    match target {
        "m1-8gb" => 3 * 1024 * 1024 * 1024,
        "m2-16gb" => 4 * 1024 * 1024 * 1024,
        _ => 3 * 1024 * 1024 * 1024,
    }
}
